/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewer;

import com.AllCalculations;
import com.ConstantData;
import com.Format;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import model.DB;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JRViewer;

/**
 *
 * @author Sudaraka Ranasinghe
 */
public class ViewGrnDetails extends javax.swing.JDialog {

    /**
     * Creates new form
     */
    String grnid;
    String grnno;
    ViewGrn viewgrn;

    public ViewGrnDetails(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public ViewGrnDetails(java.awt.Frame parent, boolean modal, String grnid, ViewGrn viewgrn) {
        super(parent, modal);
        initComponents();
        this.grnid = grnid;
        this.viewgrn= viewgrn;
        firstLoad();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barcodeprint = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblbarcode = new javax.swing.JTable();
        btnprintnow = new javax.swing.JButton();
        Jasperviewr = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblgrnid = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblgrnno = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblloguser = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblsupid = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblsuppliername = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblsupcontact = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblbranch = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblitemcount = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtgrandamount = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        lbldiscountoption = new javax.swing.JLabel();
        lbldiscount = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblfinaldiscount = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblgrandamount = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblgrn = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnprint = new javax.swing.JButton();
        btnpayment = new javax.swing.JButton();
        lblpending = new javax.swing.JLabel();
        lblcomplete = new javax.swing.JLabel();
        btnbarcode = new javax.swing.JButton();

        barcodeprint.setAlwaysOnTop(true);
        barcodeprint.setResizable(false);

        tblbarcode.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Item Name", "Barcode", "Serial No", "Qty"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblbarcode.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(tblbarcode);

        btnprintnow.setText("Print Now");
        btnprintnow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintnowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout barcodeprintLayout = new javax.swing.GroupLayout(barcodeprint.getContentPane());
        barcodeprint.getContentPane().setLayout(barcodeprintLayout);
        barcodeprintLayout.setHorizontalGroup(
            barcodeprintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barcodeprintLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barcodeprintLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnprintnow)
                .addGap(18, 18, 18))
        );
        barcodeprintLayout.setVerticalGroup(
            barcodeprintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barcodeprintLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnprintnow)
                .addContainerGap())
        );

        Jasperviewr.setAlwaysOnTop(true);
        Jasperviewr.setResizable(false);

        javax.swing.GroupLayout JasperviewrLayout = new javax.swing.GroupLayout(Jasperviewr.getContentPane());
        Jasperviewr.getContentPane().setLayout(JasperviewrLayout);
        JasperviewrLayout.setHorizontalGroup(
            JasperviewrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        JasperviewrLayout.setVerticalGroup(
            JasperviewrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GRN View Details");
        jLabel1.setOpaque(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("GRN ID");

        lblgrnid.setText("id");

        jLabel6.setText("GRN No");

        lblgrnno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblgrnno.setText("id");

        jLabel8.setText("Date");

        lbldate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbldate.setText("id");

        jLabel10.setText("Store Keeper");

        lblloguser.setText("id");

        jLabel12.setText("Supplier ID");

        lblsupid.setText("id");

        jLabel14.setText("Supplier Name");

        lblsuppliername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblsuppliername.setText("id");

        jLabel16.setText("Supplier Contact");

        lblsupcontact.setText("id");

        jLabel18.setText("Branch");

        lblbranch.setText("id");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblgrnno, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbldate, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblgrnid, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(lblloguser, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblbranch, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblsupcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblsupid, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblsuppliername, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(lblsupid))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(lblgrnid)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(lblsuppliername))
                    .addComponent(jLabel6)
                    .addComponent(lblgrnno))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(lblsupcontact))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(lbldate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(lblbranch))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(lblloguser)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Item Count");

        lblitemcount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblitemcount.setText("0");

        jLabel3.setText("Net Amount Rs.");

        txtgrandamount.setEditable(false);
        txtgrandamount.setBackground(new java.awt.Color(255, 255, 204));
        txtgrandamount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtgrandamount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtgrandamount.setText("0.0");
        txtgrandamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgrandamountActionPerformed(evt);
            }
        });

        jLabel20.setText("Discount Opt");

        lbldiscountoption.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbldiscountoption.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbldiscountoption.setText("id");

        lbldiscount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbldiscount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbldiscount.setText("id");

        jLabel23.setText("Discount");

        lblfinaldiscount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblfinaldiscount.setForeground(new java.awt.Color(0, 51, 204));
        lblfinaldiscount.setText("id");

        jLabel25.setText("Grand Amount Rs.");

        lblgrandamount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblgrandamount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblgrandamount.setText("id");

        tblgrn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Serial Type", "Batch No", "Barcode", "Serial No", "Warranty(Month)", "Qty", "Cost Price", "Discount Opt", "Discount", "Last Cost Price", "Amount Rs.", "Sell Price", "Discount Opt", "Sell Discount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblgrn.getTableHeader().setReorderingAllowed(false);
        tblgrn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblgrnMouseClicked(evt);
            }
        });
        tblgrn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblgrnKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblgrnKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblgrn);
        if (tblgrn.getColumnModel().getColumnCount() > 0) {
            tblgrn.getColumnModel().getColumn(0).setPreferredWidth(5);
            tblgrn.getColumnModel().getColumn(9).setPreferredWidth(0);
            tblgrn.getColumnModel().getColumn(14).setPreferredWidth(0);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lblitemcount, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel20)
                    .addComponent(jLabel23)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblgrandamount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbldiscount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbldiscountoption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtgrandamount, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblfinaldiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(241, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblitemcount)
                    .addComponent(jLabel3)
                    .addComponent(txtgrandamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(lbldiscountoption))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(lbldiscount)
                    .addComponent(lblfinaldiscount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(lblgrandamount))
                .addGap(10, 10, 10))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(129, Short.MAX_VALUE)))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnprint.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnprint.setText("Re-Print");

        btnpayment.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnpayment.setText("Payment");
        btnpayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpaymentActionPerformed(evt);
            }
        });

        lblpending.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblpending.setForeground(new java.awt.Color(255, 0, 0));
        lblpending.setText("Payments Pending");

        lblcomplete.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblcomplete.setForeground(new java.awt.Color(51, 204, 0));
        lblcomplete.setText("Payments Completed");

        btnbarcode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnbarcode.setText("Print Barcodes");
        btnbarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbarcodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblpending, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcomplete, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(btnpayment, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(btnbarcode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnprint, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblpending)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcomplete))
                    .addComponent(btnprint, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnpayment, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnbarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtgrandamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgrandamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgrandamountActionPerformed

    private void btnpaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpaymentActionPerformed
        if (lblpending.isVisible() && tblgrn.getRowCount() != 0) {
//            dispose();
            new DuePaymentGrn(ConstantData.home, false, grnid, grnno, lblsupid.getText().trim(),this).setVisible(true);
        }
    }//GEN-LAST:event_btnpaymentActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            viewgrn.clearAll();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_formWindowClosing

    private void tblgrnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblgrnMouseClicked

    }//GEN-LAST:event_tblgrnMouseClicked

    private void tblgrnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblgrnKeyPressed

    }//GEN-LAST:event_tblgrnKeyPressed

    private void tblgrnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblgrnKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblgrnKeyReleased

    private void btnbarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbarcodeActionPerformed
        barcodePrint();

    }//GEN-LAST:event_btnbarcodeActionPerformed

    private void btnprintnowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintnowActionPerformed
        barcodePrint();
    }//GEN-LAST:event_btnprintnowActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        System.out.println("out");
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            viewBarcodePrint();
        }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewGrnDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewGrnDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewGrnDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewGrnDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewGrnDetails dialog = new ViewGrnDetails(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Jasperviewr;
    private javax.swing.JDialog barcodeprint;
    private javax.swing.JButton btnbarcode;
    private javax.swing.JButton btnpayment;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton btnprintnow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblbranch;
    private javax.swing.JLabel lblcomplete;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbldiscount;
    private javax.swing.JLabel lbldiscountoption;
    private javax.swing.JLabel lblfinaldiscount;
    private javax.swing.JLabel lblgrandamount;
    private javax.swing.JLabel lblgrnid;
    private javax.swing.JLabel lblgrnno;
    private javax.swing.JLabel lblitemcount;
    private javax.swing.JLabel lblloguser;
    private javax.swing.JLabel lblpending;
    private javax.swing.JLabel lblsupcontact;
    private javax.swing.JLabel lblsupid;
    private javax.swing.JLabel lblsuppliername;
    private javax.swing.JTable tblbarcode;
    private javax.swing.JTable tblgrn;
    private javax.swing.JTextField txtgrandamount;
    // End of variables declaration//GEN-END:variables

    private void firstLoad() {
        lblpending.setVisible(false);
        lblcomplete.setVisible(false);
        LoadGRNDetails();

    }

    public void LoadGRNDetails() {
        try {

            ResultSet rs = model.DB.getData("SELECT\n"
                    + "grn.id,\n"
                    + "grn.grnno,\n"
                    + "grn.date,\n"
                    + "buz_man_id,\n"
                    + "buz_man.fname,\n"
                    + "buz_man.lname,\n"
                    + "buz_man.contact_1,\n"
                    + "grn.discount_opt,\n"
                    + "grn.discount,\n"
                    + "grn.grand_tot,\n"
                    + "`user`.fname,\n"
                    + "`user`.lname,\n"
                    + "branch.`name`,\n"
                    + "payment_reg.`status`,\n"
                    + "payment_rec.due\n"
                    + "FROM\n"
                    + "grn ,\n"
                    + "buz_man ,\n"
                    + "payment_reg ,\n"
                    + "`user` ,\n"
                    + "branch ,\n"
                    + "payment_rec\n"
                    + "WHERE\n"
                    + "grn.buz_man_id = buz_man.id AND\n"
                    + "grn.`status` = '1' AND\n"
                    + "grn.id = payment_reg.section_id AND\n"
                    + "payment_reg.type = 'GRN' AND\n"
                    + "grn.holder_id = `user`.id AND\n"
                    + "grn.branch_id = branch.id AND\n"
                    + "payment_rec.id = (select max(payment_rec.id) from payment_rec where payment_reg.id=payment_rec.payment_reg_id ORDER BY payment_rec.id DESC ) AND\n"
                    + "grn.id ='" + grnid.trim() + "'\n"
                    + "");

            if (rs.next()) {
                lblgrnid.setText(rs.getString(1));
                lblgrnno.setText(rs.getString(2));
                grnno = rs.getString(2);
                lbldate.setText(rs.getString(3));
                lblsupid.setText(rs.getString(4));
                lblsuppliername.setText(rs.getString(5) + " " + rs.getString(6));
                lblsupcontact.setText(rs.getString(7));

                lbldiscountoption.setText(rs.getString(8));
//                if (rs.getString(8).equals("0")) {
//                    lbldiscountoption.setText("%");
//                } else if (rs.getString(8).equals("1")) {
//                    lbldiscountoption.setText("Price");
//                }

                lbldiscount.setText(rs.getString(9));
                lblgrandamount.setText(rs.getString(10));
                lblloguser.setText(rs.getString(11) + " " + rs.getString(12));
                lblbranch.setText(rs.getString(13));

                if (rs.getString(14).equals(ConstantData.Status_PENDING)) {
                    lblpending.setVisible(true);
                    lblcomplete.setVisible(false);
                } else if (rs.getString(14).equals(ConstantData.Status_COMPLETE)) {
                    lblcomplete.setVisible(true);
                     lblpending.setVisible(false);
                }

                LoadDetails();
                Calculations_Finals(rs.getString(8), rs.getDouble(9), Double.parseDouble(txtgrandamount.getText().trim()));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void Calculations_Finals(String opt, double value, double lasttotal) {
        try {

            if (opt.equals("%")) { // %
                if (value < 100) {
//                 
                    lblfinaldiscount.setText("Rs. " + AllCalculations.DiscountforPrecentage(lasttotal, value));
                    lblgrandamount.setText(AllCalculations.DiscountforPrecentage(lasttotal, value));
                } else {

//                    Calculations_Finals();
                }

            } else//Price
             if (value <= lasttotal) {
                    double discoun = 100 - Double.parseDouble(AllCalculations.DiscountforPrice(lasttotal, value));
                    lblfinaldiscount.setText(Format.decimal3.format(discoun) + "%");
                    lblgrandamount.setText(Format.decimal3.format(lasttotal - value));
                } else {

//                    Calculations_Finals();
                }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void LoadDetails() {
        try {
            DefaultTableModel tbl = (DefaultTableModel) tblgrn.getModel();
            tbl.setRowCount(0);

            ResultSet rs = DB.getData("SELECT\n"
                    + "grn_detail.item_id,\n"
                    + "item.`name`,\n"
                    + "serialize.type,\n"
                    + "grn_detail.batch_id,\n"
                    + "serial_details.serialno,\n"
                    + "batch.warranty,\n"
                    + "grn_detail.qty,\n"
                    + "grn_detail.cost_price,\n"
                    + "grn_detail.discount_opt,\n"
                    + "grn_detail.discount,\n"
                    + "grn_detail.total,\n"
                    + "grn_detail.sell_price,\n"
                    + "batch.discount_opt,\n"
                    + "batch.discount,\n"
                    + "grn_detail.lastcost_price,"
                    + "batch.barcode\n"
                    + "FROM\n"
                    + "grn ,\n"
                    + "grn_detail ,\n"
                    + "serial_details ,\n"
                    + "serialize ,\n"
                    + "batch ,\n"
                    + "item\n"
                    + "WHERE\n"
                    + "grn.id = grn_detail.grn_id AND\n"
                    + "grn_detail.item_id = item.id AND\n"
                    + "grn.id = '" + grnid.trim() + "' AND\n"
                    + "grn_detail.batch_id = batch.id AND\n"
                    + "batch.id = serial_details.batch_id AND\n"
                    + "serial_details.serialize_id = serialize.id");

            while (rs.next()) {
                String itemid = rs.getString(1);
                String itemname = rs.getString(2);
                String serialtype = rs.getString(3);
                String batchno = rs.getString(4);
                String serialno = rs.getString(5);
                String warranty = rs.getString(6);
                double qty = rs.getDouble(7);
                double cost = rs.getDouble(8);
                String discounopcost = rs.getString(9);
                double discountcost = rs.getDouble(10);
                double lastcostprice = rs.getDouble(15);
                double amount = rs.getDouble(11);
                double sell = rs.getDouble(12);
                String discounopsell = rs.getString(13);
                double selldiscount = rs.getDouble(14);
                String barcode = rs.getString(16);

                Object arr[] = {itemid, itemname, serialtype, batchno, barcode, serialno, warranty, qty, cost,
                    discounopcost, discountcost, lastcostprice, amount, sell, discounopsell, selldiscount};
                tbl.addRow(arr);

            }

            TableItemAmountandItemCount();
            lblitemcount.setText(String.valueOf(tblgrn.getRowCount()));
            loadBarcodeTable();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void TableItemAmountandItemCount() {
        if (tblgrn.getRowCount() != 0) {

            double grandamount = 0.0;
            for (int i = 0; i < tblgrn.getRowCount(); i++) {

                grandamount += Double.parseDouble(tblgrn.getValueAt(i, 12).toString());

            }
            txtgrandamount.setText(Format.decimal3.format(grandamount));

        }
    }

    private void viewBarcodePrint() {
        barcodeprint.setSize(518, 300);
        barcodeprint.setLocationRelativeTo(this);
        barcodeprint.setModal(true);
        barcodeprint.setIconImage(ConstantData.img.getImage());
        barcodeprint.setVisible(true);

    }

    private void loadBarcodeTable() {

        try {

            DefaultTableModel tbl = (DefaultTableModel) tblbarcode.getModel();
            tbl.setRowCount(0);

            if (tblgrn.getRowCount() != 0) {

                int num = 1;

                for (int i = 0; i < tblgrn.getRowCount(); i++) {
                    String name = tblgrn.getValueAt(i, 1).toString();
                    String barcode = tblgrn.getValueAt(i, 4).toString();
                    String serial = tblgrn.getValueAt(i, 5).toString();
                    int qty = (int) Double.parseDouble(tblgrn.getValueAt(i, 7).toString());

                    for (int j = 1; j <= qty; j++) {
//                        System.out.println(num + " " + barcode + " " + qty);
                        Object arr[] = {num, name, barcode, serial, qty};
                        tbl.addRow(arr);
                        num++;
                    }

                }

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void barcodePrint() {

        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

            JRTableModelDataSource datasource = new JRTableModelDataSource(tblbarcode.getModel());
            String reportSource = ConstantData.ReportPATH + "barcode.jrxml";
            Map<String, Object> params = new HashMap<String, Object>();

            params.put("grnid", lblgrnid.getText());
            params.put("grnno", lblgrnno.getText());
            params.put("datetime", lbldate.getText());

            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);

            JasperPrint jp = JasperFillManager.fillReport(jasperReport, params, datasource);

//            JasperViewer.viewReport(jp, false);
            JDialog jDialog = new JDialog(this, true);
            jDialog.getContentPane().add(new JRViewer(jp));
            jDialog.pack();

            jDialog.setSize(1000, 700);
            jDialog.setLocationRelativeTo(this);

            jDialog.setVisible(true);

//           JasperPrintManager.printReport(jp, true);
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));

        } catch (Exception e) {
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            e.printStackTrace();
        }

    }
}
