/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewer;

import com.AllCalculations;
import com.ConstantData;
import com.Format;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JDialog;
import javax.swing.table.DefaultTableModel;
import model.DB;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JRViewer;

/**
 *
 * @author Sudaraka Ranasinghe
 */
public class ViewInvoiceDetails extends javax.swing.JDialog {

    /**
     * Creates new form
     */
    String invoiceid;
    ViewInvoice viewInvoice;

    public ViewInvoiceDetails(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public ViewInvoiceDetails(java.awt.Frame parent, boolean modal, String invoiceid, ViewInvoice viewInvoice) {
        super(parent, modal);
        initComponents();
        this.invoiceid = invoiceid;
        this.viewInvoice = viewInvoice;

        firstLoad();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblinvoiceno = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblloguser = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblcustid = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblcustomername = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblcustcontact = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblbranch = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblpobox = new javax.swing.JLabel();
        lblstreet1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblstreet2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblcity = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblitemcount = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnetamount = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        lbldiscountoption = new javax.swing.JLabel();
        lbldiscount = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblfinaldiscount = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblgrandamount = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblinvo = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtareanote = new javax.swing.JTextArea();
        lblnote = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnprint = new javax.swing.JButton();
        btnpayment = new javax.swing.JButton();
        lblpending = new javax.swing.JLabel();
        lblcomplete = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Invoice No");

        lblinvoiceno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblinvoiceno.setText("id");

        jLabel8.setText("Date");

        lbldate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbldate.setText("id");

        jLabel10.setText("Salesman");

        lblloguser.setText("id");

        jLabel12.setText("Customer ID");

        lblcustid.setText("id");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Customer Name");

        lblcustomername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcustomername.setText("id");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Customer Contact");

        lblcustcontact.setText("id");

        jLabel18.setText("Branch");

        lblbranch.setText("id");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("PoBox");

        lblpobox.setText("id");

        lblstreet1.setText("id");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Street 1");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Street 2");

        lblstreet2.setText("id");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("City");

        lblcity.setText("id");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcustid, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblcustomername, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblstreet2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblcity, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblpobox, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblstreet1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcustcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(28, 28, 28)
                        .addComponent(lblloguser, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(22, 22, 22)
                        .addComponent(lblinvoiceno, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel18))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblbranch, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbldate, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblinvoiceno))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lbldate))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblbranch)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(lblloguser)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(lblcustid))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(lblcustomername))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(lblcustcontact))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblpobox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lblstreet1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(lblstreet2)
                            .addComponent(jLabel15)
                            .addComponent(lblcity))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Item Count");

        lblitemcount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblitemcount.setText("0");

        jLabel3.setText("Net Amount Rs.");

        txtnetamount.setEditable(false);
        txtnetamount.setBackground(new java.awt.Color(255, 255, 204));
        txtnetamount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtnetamount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtnetamount.setText("0.0");
        txtnetamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnetamountActionPerformed(evt);
            }
        });

        jLabel20.setText("Discount Opt");

        lbldiscountoption.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbldiscountoption.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbldiscountoption.setText("id");

        lbldiscount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbldiscount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbldiscount.setText("id");

        jLabel23.setText("Discount");

        lblfinaldiscount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblfinaldiscount.setForeground(new java.awt.Color(0, 51, 204));
        lblfinaldiscount.setText("id");

        jLabel25.setText("Grand Amount Rs.");

        lblgrandamount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblgrandamount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblgrandamount.setText("id");

        tblinvo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Barcode No", "Serial Type", "Serial No", "Warranty(Monthly)", "Cost Price", "Sell Price", "Qty", "Discount Opt", "Discount", "Last Sell Rs.", "Amount Rs."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblinvo.getTableHeader().setReorderingAllowed(false);
        tblinvo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblinvoMouseClicked(evt);
            }
        });
        tblinvo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblinvoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblinvoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblinvo);

        txtareanote.setEditable(false);
        txtareanote.setColumns(20);
        txtareanote.setRows(5);
        txtareanote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtareanoteKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(txtareanote);

        lblnote.setText("Note");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblnote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lblitemcount, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(212, 212, 212)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel20)
                            .addComponent(jLabel23)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblgrandamount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbldiscountoption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtnetamount)
                            .addComponent(lbldiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblfinaldiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblitemcount)
                            .addComponent(jLabel3)
                            .addComponent(txtnetamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(lbldiscountoption))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(lbldiscount)
                            .addComponent(lblfinaldiscount))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(lblgrandamount)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lblnote))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnprint.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnprint.setText("Re-Print");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });

        btnpayment.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnpayment.setText("Payment");
        btnpayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpaymentActionPerformed(evt);
            }
        });

        lblpending.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblpending.setForeground(new java.awt.Color(255, 0, 0));
        lblpending.setText("Payments Pending");

        lblcomplete.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblcomplete.setForeground(new java.awt.Color(51, 204, 0));
        lblcomplete.setText("Payments Completed");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblpending, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcomplete, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(btnpayment, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214)
                .addComponent(btnprint, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblpending)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcomplete))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnpayment, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnprint, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(0, 0, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Invoice Details");
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnetamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnetamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnetamountActionPerformed

    private void btnpaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpaymentActionPerformed
        if (lblpending.isVisible() && tblinvo.getRowCount() != 0) {
//            dispose();
            new DuePaymentInvoice(ConstantData.home, false, invoiceid, lblcustid.getText().trim(), this).setVisible(true);
        }
    }//GEN-LAST:event_btnpaymentActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            viewInvoice.clearAll();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_formWindowClosing

    private void tblinvoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblinvoMouseClicked

    }//GEN-LAST:event_tblinvoMouseClicked

    private void tblinvoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblinvoKeyPressed

    }//GEN-LAST:event_tblinvoKeyPressed

    private void tblinvoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblinvoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblinvoKeyReleased

    private void txtareanoteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtareanoteKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            btnpayment.grabFocus();
        }
    }//GEN-LAST:event_txtareanoteKeyPressed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        PrintA5Invaoice();
    }//GEN-LAST:event_btnprintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewInvoiceDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewInvoiceDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewInvoiceDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewInvoiceDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewInvoiceDetails dialog = new ViewInvoiceDetails(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpayment;
    private javax.swing.JButton btnprint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblbranch;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lblcomplete;
    private javax.swing.JLabel lblcustcontact;
    private javax.swing.JLabel lblcustid;
    private javax.swing.JLabel lblcustomername;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbldiscount;
    private javax.swing.JLabel lbldiscountoption;
    private javax.swing.JLabel lblfinaldiscount;
    private javax.swing.JLabel lblgrandamount;
    private javax.swing.JLabel lblinvoiceno;
    private javax.swing.JLabel lblitemcount;
    private javax.swing.JLabel lblloguser;
    private javax.swing.JLabel lblnote;
    private javax.swing.JLabel lblpending;
    private javax.swing.JLabel lblpobox;
    private javax.swing.JLabel lblstreet1;
    private javax.swing.JLabel lblstreet2;
    private javax.swing.JTable tblinvo;
    private javax.swing.JTextArea txtareanote;
    private javax.swing.JTextField txtnetamount;
    // End of variables declaration//GEN-END:variables

    private void firstLoad() {
        lblpending.setVisible(false);
        lblcomplete.setVisible(false);
        LoadINVOICEDetails();

    }

    public void LoadINVOICEDetails() {
        try {

            ResultSet rs = model.DB.getData("SELECT\n"
                    + "invoice.id,\n"
                    + "invoice.date,\n"
                    + "buz_man_id,\n"
                    + "buz_man.fname,\n"
                    + "buz_man.lname,\n"
                    + "buz_man.contact_1,\n"
                    + "invoice.discount_opt,\n"
                    + "invoice.discount,\n"
                    + "invoice.grand_tot,\n"
                    + "`user`.fname,\n"
                    + "`user`.lname,\n"
                    + "branch.`name`,\n"
                    + "payment_reg.`status`,\n"
                    + "payment_rec.due,\n"
                    + "invoice.note,\n"
                    + "buz_man.pobox,\n"
                    + "buz_man.street_1,\n"
                    + "buz_man.street_2,\n"
                    + "buz_man.city\n"
                    + "FROM\n"
                    + "invoice ,\n"
                    + "buz_man ,\n"
                    + "payment_reg ,\n"
                    + "`user` ,\n"
                    + "branch ,\n"
                    + "payment_rec\n"
                    + "WHERE\n"
                    + "invoice.buz_man_id = buz_man.id AND\n"
                    + "invoice.`status` = '1' AND\n"
                    + "invoice.id = payment_reg.section_id AND\n"
                    + "payment_reg.type = 'INVOICE' AND\n"
                    + "invoice.holder_id = `user`.id AND\n"
                    + "invoice.branch_id = branch.id AND\n"
                    + "payment_rec.id = (select max(payment_rec.id) from payment_rec where payment_reg.id=payment_rec.payment_reg_id ORDER BY payment_rec.id DESC ) AND\n"
                    + "invoice.id ='" + invoiceid.trim() + "'\n"
                    + "");

            if (rs.next()) {

                lblinvoiceno.setText(rs.getString(1));
                lbldate.setText(rs.getString(2));
                lblcustid.setText(rs.getString(3));
                lblcustomername.setText(rs.getString(4) + " " + rs.getString(5));
                lblcustcontact.setText(rs.getString(6));

                lbldiscountoption.setText(rs.getString(7));
//            
                lbldiscount.setText(rs.getString(8));
                lblgrandamount.setText(rs.getString(9));
                lblloguser.setText(rs.getString(10) + " " + rs.getString(11));
                lblbranch.setText(rs.getString(12));

                if (rs.getString(13).equals(ConstantData.Status_PENDING)) {
                    lblpending.setVisible(true);
                    lblcomplete.setVisible(false);
                } else if (rs.getString(13).equals(ConstantData.Status_COMPLETE)) {
                    lblcomplete.setVisible(true);
                    lblpending.setVisible(false);
                }

                txtareanote.setText(rs.getString(15));
                lblpobox.setText(rs.getString(16));
                lblstreet1.setText(rs.getString(17));
                lblstreet2.setText(rs.getString(18));
                lblcity.setText(rs.getString(19));

                LoadDetails();
                Calculations_Finals(rs.getString(7), rs.getDouble(8), Double.parseDouble(txtnetamount.getText().trim()));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void Calculations_Finals(String opt, double value, double lasttotal) {
        try {

            if (opt.equals("%")) { // %
                if (value < 100) {
//                 
                    lblfinaldiscount.setText("Rs. " + AllCalculations.DiscountforPrecentage(lasttotal, value));
                    lblgrandamount.setText(AllCalculations.DiscountforPrecentage(lasttotal, value));
                } else {

//                    Calculations_Finals();
                }

            } else//Price
            {
                if (value <= lasttotal) {
                    double discoun = 100 - Double.parseDouble(AllCalculations.DiscountforPrice(lasttotal, value));
                    lblfinaldiscount.setText(Format.decimal3.format(discoun) + "%");
                    lblgrandamount.setText(Format.decimal3.format(lasttotal - value));
                } else {

//                    Calculations_Finals();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void LoadDetails() {
        try {
            DefaultTableModel tbl = (DefaultTableModel) tblinvo.getModel();
            tbl.setRowCount(0);

            ResultSet rs = DB.getData("SELECT\n"
                    + "invoice_detail.item_id,\n"
                    + "item.`name`,\n"
                    + "batch.barcode,\n"
                    + "serialize.type,\n"
                    + "serial_details.serialno,\n"
                    + "invoice_detail.warranty,\n"
                    + "invoice_detail.cost_price,\n"
                    + "invoice_detail.sell_price,\n"
                    + "invoice_detail.qty,\n"
                    + "invoice_detail.discount_opt,\n"
                    + "invoice_detail.discount,\n"
                    + "invoice_detail.last_sell,\n"
                    + "invoice_detail.total\n"
                    + "FROM\n"
                    + "invoice_detail ,\n"
                    + "batch ,\n"
                    + "item ,\n"
                    + "serial_details ,\n"
                    + "serialize\n"
                    + "WHERE\n"
                    + "invoice_detail.invoice_id = '" + invoiceid.trim() + "' AND\n"
                    + "invoice_detail.batch_id = batch.id AND\n"
                    + "invoice_detail.item_id = item.id AND\n"
                    + "invoice_detail.batch_id = serial_details.batch_id AND\n"
                    + "invoice_detail.batch_id = serial_details.batch_id AND\n"
                    + "serial_details.serialize_id = serialize.id");

            while (rs.next()) {
                String itemid = rs.getString(1);
                String itemname = rs.getString(2);

                String barcode = rs.getString(3);
                String serialtype = rs.getString(4);
                String serialno = rs.getString(5);
                String warranty = rs.getString(6);
                double cost = rs.getDouble(7);
                double sell = rs.getDouble(8);
                double qty = rs.getDouble(9);

                String discounopcost = rs.getString(10);
                double discount = rs.getDouble(11);
                double lastprice = rs.getDouble(12);
                double amount = rs.getDouble(13);

                Object arr[] = {itemid, itemname, barcode, serialtype, serialno, warranty, cost, sell, qty, discounopcost, discount, lastprice, amount};
                tbl.addRow(arr);

            }

            TableItemAmountandItemCount();
            lblitemcount.setText(String.valueOf(tblinvo.getRowCount()));

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void TableItemAmountandItemCount() {
        if (tblinvo.getRowCount() != 0) {

            double grandamount = 0.0;
            for (int i = 0; i < tblinvo.getRowCount(); i++) {

                grandamount += Double.parseDouble(tblinvo.getValueAt(i, 12).toString());

            }
            txtnetamount.setText(Format.decimal3.format(grandamount));

        }
    }

//    private String getBarcode(String batchid) {
//        String id = "0";
//        try {
//            ResultSet rs = DB.getData("SELECT\n"
//                    + "batch.barcode\n"
//                    + "FROM\n"
//                    + "batch\n"
//                    + "WHERE\n"
//                    + "batch.id = '" + batchid.trim() + "'");
//            if (rs.next()) {
//                id = rs.getString(1);
//            }
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//
//        return id;
//
//    }
    private void PrintA5Invaoice() {
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

            JRTableModelDataSource datasource = new JRTableModelDataSource(tblinvo.getModel());// for table
            String reportSource = ConstantData.ReportPATH + "invoiceA5.jrxml";
            Map<String, Object> params = new HashMap<String, Object>();

            params.put("id", lblinvoiceno.getText());
            params.put("datetime", lbldate.getText());
            //------------------------------------------------------

            params.put("branch", lblbranch.getText());
            params.put("holder", lblloguser.getText());
            params.put("cusname", lblcustomername.getText());

            if (!lblcustid.getText().equals("1")) {
                params.put("cuscontact", lblcustcontact.getText());
                params.put("pobox", lblpobox.getText() + ",");
                params.put("st1", lblstreet1.getText() + ",");
                params.put("st2", lblstreet2.getText() + ",");
                params.put("city", lblcity.getText());
            }

            //---------------------------------------------------------------------------
//            params.put("paymethod", invoicepay.cmbpaymethod.getSelectedItem().toString());
            params.put("netamount", Double.parseDouble(txtnetamount.getText()));
            params.put("op", lbldiscountoption.getText());
            params.put("discount", Double.parseDouble(lbldiscount.getText()));
            params.put("grandamount", Double.parseDouble(lblgrandamount.getText()));

            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);

            JasperPrint jp = JasperFillManager.fillReport(jasperReport, params, datasource);

//            JasperViewer.viewReport(jp, false);
            JDialog jDialog = new JDialog(this, true);
            jDialog.getContentPane().add(new JRViewer(jp));
            jDialog.pack();

            jDialog.setSize(1000, 700);
            jDialog.setLocationRelativeTo(this);

            jDialog.setVisible(true);

//           JasperPrintManager.printReport(jp, true);
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));

        } catch (Exception e) {
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            e.printStackTrace();
        }

    }

}
